"""crear_tablas_ordenes_productos

Revision ID: 89d46bb07139
Revises: 
Create Date: 2026-04-11 03:50:18.267001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d46bb07139'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marketplace', sa.Enum('walmart', 'paris', 'falabella', 'ripley', name='marketplaceenum'), nullable=False),
    sa.Column('orden_id_marketplace', sa.String(length=100), nullable=False),
    sa.Column('sub_orden_id', sa.String(length=100), nullable=True),
    sa.Column('cliente_nombre', sa.String(length=200), nullable=True),
    sa.Column('estado_marketplace', sa.String(length=100), nullable=True),
    sa.Column('estado_interno', sa.Enum('pendiente', 'confirmada', 'lista_despacho', 'despachada', 'entregada', 'cancelada', name='estadoordenenum'), nullable=False),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('fecha_despacho', sa.String(length=50), nullable=True),
    sa.Column('fecha_llegada', sa.String(length=50), nullable=True),
    sa.Column('label_url', sa.String(length=500), nullable=True),
    sa.Column('fecha_marketplace', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_marketplace'), 'ordenes', ['marketplace'], unique=False)
    op.create_index(op.f('ix_ordenes_orden_id_marketplace'), 'ordenes', ['orden_id_marketplace'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('material', sa.String(length=200), nullable=True),
    sa.Column('acabado', sa.String(length=200), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('alto_cm', sa.Float(), nullable=True),
    sa.Column('ancho_cm', sa.Float(), nullable=True),
    sa.Column('profundo_cm', sa.Float(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('precio_costo', sa.Float(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('skus_marketplaces', sa.JSON(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_sku'), 'productos', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_sku'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_ordenes_orden_id_marketplace'), table_name='ordenes')
    op.drop_index(op.f('ix_ordenes_marketplace'), table_name='ordenes')
    op.drop_table('ordenes')
    # ### end Alembic commands ###
